### PR TITLE
Add CodeQL security scanning

### PR DESCRIPTION
**Pull request by jhutchings1**
Hi, I'm a PM on the GitHub security team. This repository is eligible to try the new [GitHub Advanced Security code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) beta.

Code scanning runs a static analysis tool called CodeQL which scans your code at build time to find any potential security issues. We've tuned the set of queries to be only the most severe, most precise issues. We'll show alerts in the security tab, and we'll show alerts for any net new vulnerabilities on pull requests as well. We've tried to make this super developer friendly, but we'd love your feedback as we work through the beta. 

If you're interested in trying it out, you can merge this pull request to set up the Actions workflow.

### CODE REVIEW

**Comment by ds-ms** [comment]
👋 @jhutchings1 

Thank you for the PR. We're excited to onboard onto the code-ql functionalities 😄 
Mark it `Ready for review` once you're done; I'll take this PR forward

**Comment by jhutchings1** [comment]
Thanks @ds-ms! The build is working, so I think this is good to merge. There are some issues that this found, so I'd suggest having a look in the security tab as soon as the build completes.

**Comment by ds-ms** [comment]
Although the workflow is executed, this still shows up for me
image

Is this expected? Or is it expected to go away after the check-in?

**Comment by jhutchings1** [comment]
> Although the workflow is executed, this still shows up for me
> image
> 
> Is this expected? Or is it expected to go away after the check-in?

Yeah, that's because until you merge the changes, there are no analyses in this repository. Once it's merged, the state will live here instead of the fork.

**Comment by ds-ms** [comment]
@jhutchings1 it works perfectly, I see some vulnerabilities found; we'll take an action item to fix them 😃

**Pull request merged**
